'use client'

import { useEffect, useState } from 'react'
import type { ExecDecision } from '@/lib/director/types'
import {
  parseBrief,
  type BriefConfidence,
  type PhaseGateBrief,
} from '@/lib/director/phase-gate-brief-parser'

type StreamState =
  | { kind: 'streaming'; text: string }
  | { kind: 'done'; brief: PhaseGateBrief }
  | { kind: 'error'; message: string }

const CONFIDENCE_BADGE: Record<BriefConfidence, string> = {
  high: 'bg-[#6FA37A]/20 text-[#A8D4B5] border border-[#6FA37A]/50',
  medium: 'bg-amber-900/40 text-amber-200 border border-amber-700/50',
  low: 'bg-[#A85D5D]/25 text-[#E6B5B5] border border-[#A85D5D]/60',
}

export function PhaseGateBriefPanel({
  lane,
  phase,
  fallback,
  onClose,
}: {
  lane: string
  phase: string
  fallback: ExecDecision | null
  onClose: () => void
}) {
  const [state, setState] = useState<StreamState>({ kind: 'streaming', text: '' })
  const fetchKey = `${lane}::${phase}`

  useEffect(() => {
    const ctrl = new AbortController()
    let cancelled = false

    const timeout = setTimeout(() => ctrl.abort(), 45_000)

    ;(async () => {
      try {
        const res = await fetch('/api/director/phasegate-brief', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ lane, phase }),
          signal: ctrl.signal,
        })
        if (!res.ok || !res.body) {
          throw new Error(`HTTP ${res.status}`)
        }
        const reader = res.body.getReader()
        const decoder = new TextDecoder()
        let buffer = ''
        while (true) {
          const { value, done } = await reader.read()
          if (done) break
          buffer += decoder.decode(value, { stream: true })
          if (cancelled) return
          const errMatch = buffer.match(/\[ERROR:\s*([^\]]+)\]/)
          if (errMatch) {
            setState({ kind: 'error', message: errMatch[1] })
            return
          }
          setState({ kind: 'streaming', text: buffer })
        }
        if (cancelled) return
        if (!buffer.trim()) {
          setState({ kind: 'error', message: 'Empty response from agent' })
          return
        }
        const brief = parseBrief(buffer, {
          owner: fallback?.owner,
          target_date: fallback?.target_date,
        })
        setState({ kind: 'done', brief })
      } catch (e) {
        if (cancelled) return
        const msg = e instanceof Error ? e.message : 'Unknown error'
        if (msg.toLowerCase().includes('abort')) {
          setState({ kind: 'error', message: 'Request timed out after 45s' })
          return
        }
        setState({ kind: 'error', message: msg })
      } finally {
        clearTimeout(timeout)
      }
    })()

    return () => {
      cancelled = true
      ctrl.abort()
      clearTimeout(timeout)
    }
  }, [fetchKey, lane, phase, fallback])

  const laneLabel = lane.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
  const phaseLabel = phase.replace(/\b\w/g, (c) => c.toUpperCase())

  return (
    <div className="mt-6 bg-gray-900 border border-amber-800/50 border-l-[3px] border-l-amber-500 rounded-lg p-4">
      <div className="flex items-start justify-between gap-3 mb-3">
        <div>
          <div className="text-[10px] text-amber-300 font-bold uppercase tracking-wider mb-1">
            Executive Escalation Brief
          </div>
          <h2 className="text-sm font-bold text-white">
            {laneLabel} × {phaseLabel}
          </h2>
          <p className="text-[11px] text-gray-500 mt-0.5">
            Generated by Phase-Gate Brief Agent · claude-sonnet-4-5
          </p>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="text-gray-500 hover:text-gray-300 transition-colors text-xs font-bold uppercase tracking-wider px-2 py-1 rounded hover:bg-gray-800"
          aria-label="Close brief"
        >
          ✕ Close
        </button>
      </div>

      {state.kind === 'streaming' && <StreamingView text={state.text} />}
      {state.kind === 'done' && <DoneView brief={state.brief} />}
      {state.kind === 'error' && (
        <ErrorView message={state.message} fallback={fallback} />
      )}
    </div>
  )
}

function StreamingView({ text }: { text: string }) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-2">
        <span className="inline-block w-2 h-2 rounded-full bg-amber-400 animate-pulse" />
        <span className="text-[10px] text-amber-300 font-bold uppercase tracking-wider">
          Streaming
        </span>
      </div>
      <pre className="text-[12px] text-gray-200 leading-relaxed whitespace-pre-wrap font-mono">
        {text || ' '}
      </pre>
    </div>
  )
}

function DoneView({ brief }: { brief: PhaseGateBrief }) {
  return (
    <div className="space-y-3">
      <Section label="Issue" body={brief.issue} />
      <Section label="Recommendation" body={brief.recommendation} highlight />
      <div className="grid grid-cols-3 gap-3 pt-1">
        <Field label="Confidence">
          <span
            className={`inline-block px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${CONFIDENCE_BADGE[brief.confidence]}`}
          >
            {brief.confidence}
          </span>
        </Field>
        <Field label="Decision owner">
          <span className="text-xs text-gray-200 font-bold">{brief.decision_owner}</span>
        </Field>
        <Field label="Decision by">
          <span className="text-xs text-gray-200 font-bold">{brief.decision_by}</span>
        </Field>
      </div>
      {brief.rationale && (
        <div className="pt-2 border-t border-gray-800">
          <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">
            Rationale
          </div>
          <p className="text-xs text-gray-300 leading-relaxed">{brief.rationale}</p>
        </div>
      )}
    </div>
  )
}

function Section({
  label,
  body,
  highlight,
}: {
  label: string
  body: string
  highlight?: boolean
}) {
  return (
    <div>
      <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">
        {label}
      </div>
      <p
        className={`text-xs leading-relaxed ${highlight ? 'text-white font-medium' : 'text-gray-200'}`}
      >
        {body || <span className="text-gray-500 italic">no content</span>}
      </p>
    </div>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">
        {label}
      </div>
      {children}
    </div>
  )
}

function ErrorView({
  message,
  fallback,
}: {
  message: string
  fallback: ExecDecision | null
}) {
  return (
    <div>
      <div className="mb-3 px-3 py-2 bg-[#A85D5D]/15 border border-[#A85D5D]/40 rounded text-[11px] text-[#E6B5B5]">
        <span className="font-bold uppercase tracking-wider mr-1">Brief generation failed:</span>
        {message}
      </div>
      {fallback ? (
        <div>
          <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-2">
            Falling back to registered executive decision
          </div>
          <div className="border border-gray-800 rounded bg-gray-900/60 p-3 space-y-2">
            <div>
              <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">
                Title
              </div>
              <p className="text-xs text-white font-bold">{fallback.title}</p>
            </div>
            <div>
              <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">
                Detail
              </div>
              <p className="text-xs text-gray-200 leading-relaxed">{fallback.detail}</p>
            </div>
            <div className="grid grid-cols-3 gap-3 pt-1 border-t border-gray-800">
              <Field label="Owner">
                <span className="text-xs text-gray-200 font-bold">{fallback.owner}</span>
              </Field>
              <Field label="Escalate to">
                <span className="text-xs text-gray-200 font-bold">{fallback.escalate_to}</span>
              </Field>
              <Field label="Decision by">
                <span className="text-xs text-gray-200 font-bold">{fallback.target_date}</span>
              </Field>
            </div>
          </div>
        </div>
      ) : (
        <p className="text-xs text-gray-400 italic">
          No registered executive decision available for this cell.
        </p>
      )}
    </div>
  )
}
