'use client'

import { useEffect, useState, type ReactNode } from 'react'
import type { CommitmentStatus } from '@/lib/director/types'
import {
  parseRoadmapComms,
  type RoadmapComms,
} from '@/lib/director/roadmap-comms-parser'

type StreamState =
  | { kind: 'streaming'; text: string }
  | { kind: 'done'; comms: RoadmapComms }
  | { kind: 'error'; message: string }

const PANEL_FRAME: Record<CommitmentStatus, string> = {
  slip: 'border-[#A85D5D]/40 border-l-[#A85D5D]',
  at_risk: 'border-amber-800/50 border-l-amber-500',
  on_track: 'border-[#6FA37A]/40 border-l-[#6FA37A]',
}

const HEADER_LABEL: Record<CommitmentStatus, string> = {
  slip: 'Customer Comms · Schedule Revision',
  at_risk: 'Customer Comms · Status Watch',
  on_track: 'Customer Comms',
}

const HEADER_TEXT: Record<CommitmentStatus, string> = {
  slip: 'text-[#E6B5B5]',
  at_risk: 'text-amber-300',
  on_track: 'text-[#A8D4B5]',
}

const PULSE: Record<CommitmentStatus, string> = {
  slip: 'bg-[#E6B5B5]',
  at_risk: 'bg-amber-400',
  on_track: 'bg-[#A8D4B5]',
}

export function RoadmapCommsPanel({
  customer,
  commitment,
  status,
  onClose,
}: {
  customer: string
  commitment: string
  status: CommitmentStatus
  onClose: () => void
}) {
  const [state, setState] = useState<StreamState>({ kind: 'streaming', text: '' })

  useEffect(() => {
    const ctrl = new AbortController()
    let cancelled = false

    const timeout = setTimeout(() => ctrl.abort(), 45_000)

    ;(async () => {
      try {
        const res = await fetch('/api/director/roadmap-comms', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ customer, commitment }),
          signal: ctrl.signal,
        })
        if (!res.ok || !res.body) {
          throw new Error(`HTTP ${res.status}`)
        }
        const reader = res.body.getReader()
        const decoder = new TextDecoder()
        let buffer = ''
        while (true) {
          const { value, done } = await reader.read()
          if (done) break
          buffer += decoder.decode(value, { stream: true })
          if (cancelled) return
          const errMatch = buffer.match(/\[ERROR:\s*([^\]]+)\]/)
          if (errMatch) {
            setState({ kind: 'error', message: errMatch[1] })
            return
          }
          setState({ kind: 'streaming', text: buffer })
        }
        if (cancelled) return
        if (!buffer.trim()) {
          setState({ kind: 'error', message: 'Empty response from agent' })
          return
        }
        const comms = parseRoadmapComms(buffer, status)
        setState({ kind: 'done', comms })
      } catch (e) {
        if (cancelled) return
        const msg = e instanceof Error ? e.message : 'Unknown error'
        if (msg.toLowerCase().includes('abort')) {
          setState({ kind: 'error', message: 'Request timed out after 45s' })
          return
        }
        setState({ kind: 'error', message: msg })
      } finally {
        clearTimeout(timeout)
      }
    })()

    return () => {
      cancelled = true
      ctrl.abort()
      clearTimeout(timeout)
    }
  }, [customer, commitment, status])

  return (
    <div className={`my-3 bg-gray-900 border border-l-[3px] rounded-lg p-4 ${PANEL_FRAME[status]}`}>
      <div className="flex items-start justify-between gap-3 mb-3">
        <div>
          <div className={`text-[10px] font-bold uppercase tracking-wider mb-1 ${HEADER_TEXT[status]}`}>
            {HEADER_LABEL[status]}
          </div>
          <h2 className="text-sm font-bold text-white">{customer}</h2>
          <p className="text-[11px] text-gray-500 mt-0.5">
            {commitment} · Generated by Roadmap Comms Generator · claude-sonnet-4-5
          </p>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="text-gray-500 hover:text-gray-300 transition-colors text-xs font-bold uppercase tracking-wider px-2 py-1 rounded hover:bg-gray-800"
          aria-label="Close customer comms"
        >
          ✕ Close
        </button>
      </div>

      {state.kind === 'streaming' && (
        <StreamingView
          text={state.text}
          pulseClass={PULSE[status]}
          headerClass={HEADER_TEXT[status]}
        />
      )}
      {state.kind === 'done' && <DoneView comms={state.comms} />}
      {state.kind === 'error' && <ErrorView message={state.message} />}
    </div>
  )
}

function StreamingView({
  text,
  pulseClass,
  headerClass,
}: {
  text: string
  pulseClass: string
  headerClass: string
}) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-2">
        <span className={`inline-block w-2 h-2 rounded-full animate-pulse ${pulseClass}`} />
        <span className={`text-[10px] font-bold uppercase tracking-wider ${headerClass}`}>
          Streaming
        </span>
      </div>
      <pre className="text-[12px] text-gray-200 leading-relaxed whitespace-pre-wrap font-mono">
        {text || ' '}
      </pre>
    </div>
  )
}

function DoneView({ comms }: { comms: RoadmapComms }) {
  return (
    <div className="space-y-3">
      {comms.subject && (
        <div>
          <Label>Subject</Label>
          <p className="text-sm text-white font-bold leading-snug">{comms.subject}</p>
        </div>
      )}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pb-2 border-b border-gray-800">
        <MetaField label="To" value={comms.to} />
        <MetaField label="From" value={comms.from} />
        <MetaField label="Re" value={comms.re} />
      </div>
      {comms.situation && <Section label="Situation" body={comms.situation} />}
      {comms.impact && <Section label="Impact" body={comms.impact} highlight />}
      {comms.mitigation && <Section label="Mitigation / Next Steps" body={comms.mitigation} />}
      {comms.escalation && <Section label="Escalation Path" body={comms.escalation} />}
      {comms.sign_off && (
        <div className="pt-2 border-t border-gray-800">
          <Label>Sign-off</Label>
          <p className="text-xs text-gray-200 leading-relaxed whitespace-pre-wrap">
            {comms.sign_off}
          </p>
        </div>
      )}
    </div>
  )
}

function Label({ children }: { children: ReactNode }) {
  return (
    <div className="text-[10px] text-gray-500 font-bold uppercase tracking-wider mb-1">
      {children}
    </div>
  )
}

function MetaField({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <Label>{label}</Label>
      <p className="text-xs text-gray-200 leading-relaxed">
        {value || <span className="text-gray-500 italic">—</span>}
      </p>
    </div>
  )
}

function Section({
  label,
  body,
  highlight,
}: {
  label: string
  body: string
  highlight?: boolean
}) {
  return (
    <div>
      <Label>{label}</Label>
      <p
        className={`text-xs leading-relaxed whitespace-pre-wrap ${
          highlight ? 'text-white font-medium' : 'text-gray-200'
        }`}
      >
        {body || <span className="text-gray-500 italic">no content</span>}
      </p>
    </div>
  )
}

function ErrorView({ message }: { message: string }) {
  return (
    <div className="px-3 py-2 bg-[#A85D5D]/15 border border-[#A85D5D]/40 rounded text-[11px] text-[#E6B5B5]">
      <span className="font-bold uppercase tracking-wider mr-1">
        Comms generation failed:
      </span>
      {message}
    </div>
  )
}
